# Generated by Django 4.0.10 on 2023-12-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('packageImage', models.CharField(blank=True, max_length=400)),
                ('packageName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pricePmonth', models.IntegerField(blank=True)),
                ('pricePyear', models.IntegerField(blank=True)),
                ('features', models.CharField(max_length=1000)),
                ('numberOfuploads', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('fullName', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=60, unique=True)),
                ('userName', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(default='free', on_delete=django.db.models.deletion.SET_DEFAULT, to='malero.packages')),
            ],
        ),
    ]
