# Generated by Django 4.0.10 on 2023-12-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('cardNumber', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nameOnCard', models.CharField(blank=True, max_length=50)),
                ('expiryDate', models.IntegerField(blank=True)),
                ('cvv', models.IntegerField(blank=True)),
                ('value', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('couponCode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('isPercentage', models.BooleanField(default=False)),
                ('numberOfUses', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True)),
                ('expiryDate', models.DateTimeField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=400)),
                ('pdfName', models.CharField(blank=True, max_length=100)),
                ('isBenign', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='malero.customers')),
            ],
        ),
    ]
