# Generated by Django 4.0.10 on 2023-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0004_packages_keyname_alter_packages_packagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='keyName',
        ),
        migrations.AlterField(
            model_name='packages',
            name='packageName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
