# Generated by Django 4.0.10 on 2023-12-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0005_remove_packages_keyname_alter_packages_packagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='keyName',
            field=models.CharField(max_length=30, null=False, blank=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packageName',
            field=models.CharField(default='free', max_length=30, primary_key=True, serialize=False),
        ),
    ]
