# Generated by Django 4.0.10 on 2023-12-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0008_packages_keyname_alter_packages_packagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='malero.packages'),
        ),
    ]
