# Generated by Django 4.0.10 on 2023-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0009_alter_customers_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='keyName',
        ),
        migrations.AddField(
            model_name='packages',
            name='NameFront',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packageName',
            field=models.CharField(default='free', max_length=30, primary_key=True, serialize=False),
        ),
    ]
