# Generated by Django 4.0.10 on 2023-12-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0011_remove_packages_namefront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='period',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
