# Generated by Django 4.0.10 on 2023-12-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0014_packages_keyname_alter_packages_packagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='keyName',
        ),
    ]
