# Generated by Django 4.0.10 on 2023-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0015_remove_packages_keyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='frontName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
