# Generated by Django 4.0.10 on 2023-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0016_packages_frontname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='pricePmonth',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='packages',
            name='pricePyear',
            field=models.CharField(max_length=30),
        ),
    ]
