# Generated by Django 4.0.10 on 2024-01-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0017_alter_packages_pricepmonth_alter_packages_pricepyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='pdfName',
        ),
        migrations.AddField(
            model_name='uploads',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/pdfs/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/'),
        ),
    ]
