# Generated by Django 4.0.10 on 2024-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0018_remove_uploads_pdfname_uploads_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='image',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='pdf',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
