# Generated by Django 4.0.10 on 2024-01-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0019_alter_uploads_image_alter_uploads_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
