# Generated by Django 4.0.10 on 2024-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0021_pdfupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='maxOfuploads',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='numberOfuploads',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='malero/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='pdf',
            field=models.FileField(upload_to='malero/uploads/pdfs/'),
        ),
    ]
