# Generated by Django 4.0.10 on 2024-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0022_remove_customers_maxofuploads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
