# Generated by Django 4.0.10 on 2024-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0023_alter_customers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='maxOfuploads',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='customers',
            name='numberOfuploads',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
