# Generated by Django 4.0.10 on 2024-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0024_customers_maxofuploads_customers_numberofuploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='expiryDateCard',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='nameOnCard',
        ),
    ]
