# Generated by Django 4.0.10 on 2024-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0025_remove_orders_cvv_remove_orders_expirydatecard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cardNumber',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
