# Generated by Django 4.0.10 on 2024-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0028_alter_cards_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='endTimeForPackage',
            field=models.DateTimeField(blank=True, default='2021-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='customers',
            name='startTimeForPackage',
            field=models.DateTimeField(blank=True, default='2021-01-01 00:00:00'),
        ),
    ]
