# Generated by Django 4.0.10 on 2024-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0029_customers_endtimeforpackage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='numberOfuploads',
        ),
        migrations.AddField(
            model_name='packages',
            name='numberOfuploadsPerMonth',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='packages',
            name='numberOfuploadsPerYear',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='packages',
            name='pricePmonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='pricePyear',
            field=models.IntegerField(),
        ),
    ]
