# Generated by Django 4.0.10 on 2024-02-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0030_remove_packages_numberofuploads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='expiryDateOrder',
        ),
    ]
