# Generated by Django 4.0.10 on 2024-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0031_remove_orders_expirydateorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='availableUploads',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
