# Generated by Django 4.0.10 on 2024-02-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malero', '0034_testuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
